[build]
builder = "nixpacks"
buildCommand = "dotnet restore ./WILMA_Backend/WILMA_Backend.csproj"
startCommand = "dotnet run --project ./WILMA_Backend/WILMA_Backend.csproj"

[variables]
DOTNET_VERSION = "8.0.0"
